# services:
#   qdrant:
#     image: qdrant/qdrant:v1.9.0
#     ports: ["6333:6333", "6334:6334"]
#     environment:
#       QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
#     volumes:
#       - G:/qdrant_data:/qdrant/storage:rw


version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: qdrant
    ports:
      - "6333:6333"  # REST API & Dashboard
      - "6334:6334"  # gRPC API
    environment:
      QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
    volumes:
      # Map your NAS folder directly
      - "G:/qdrant_data:/qdrant/storage:rw"
    restart: unless-stopped

